apiVersion: apps/v1
kind: Deployment
metadata: 
  name: my-deployment
  labels:
    team: dev1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - image: aputra/myapp-193:v6
          name: my-container-1
          ports:
            - containerPort: 8080

---

apiVersion: apps/v1
kind: Service
metadata:
  name: my-service
spec:
  type: ClusterIP
  ports:
    - port: 7070
      targetPort: 8080
  selector:
    app: my-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
spec:
  rules:
    - host: api.example.pvt
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: my-service
                port:
                  number: 7070

---


